### ISSUE TITLE
Run.sh gives error after starting

### ISSUE THREAD

**Issue by thecerial** [tokestermw/tensorflow-shakespeare#1]
This is a trace what happens:

basti@n095:/home/basti/tensorflow/tensorflow-shakespeare# sh run.sh
ROOT_DIR /home/basti/tensorflow/tensorflow-shakespeare
CACHE_DIR /home/basti/tensorflow/tensorflow-shakespeare/cache
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 8
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 8
Creating 2 layers of 256 units.

Created model with fresh parameters.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/basti/tensorflow/tensorflow-shakespeare/tensorshake/translate/translate.py", line 295, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/basti/tensorflow/tensorflow-shakespeare/tensorshake/translate/translate.py", line 292, in main
    train()
  File "/home/basti/tensorflow/tensorflow-shakespeare/tensorshake/translate/translate.py", line 158, in train
    model = create_model(sess, False)
  File "/home/basti/tensorflow/tensorflow-shakespeare/tensorshake/translate/translate.py", line 139, in create_model
    session.run(tf.variables.initialize_all_variables())

**Comment by tokestermw** [comment]
Is this the entire stack trace?

One possibility is the `--train-dir` does not exist yet.

So `mkdir /tmp/tensorflow` or whatever folder you'd like to save the model in.

**Comment by thecerial** [comment]
I have changed tensorshake/translate/translate.py line 139:

  print("Created model with fresh parameters.")
   # session.run(tf.variables.initialize_all_variables())
    session.run(tf.initialize_all_variables())

This seems to work

**Comment by tokestermw** [comment]
Weird not sure why it would make a difference. Changed here.

https://github.com/tokestermw/tensorflow-shakespeare/commit/9d80fd6b20f50c09c9b529c5950fe2f4efbe74fb
