### ISSUE TITLE
multiple values for keyword argument 'softmax_loss_function'

### ISSUE THREAD

**Issue by trideeprath** [tokestermw/tensorflow-shakespeare#4]
trideep@trideep-HP-ENVY-x360-m6-Convertible:~/Downloads/tensorflow-shakespeare-master$ ./run.sh
en_train /home/trideep/Downloads/tensorflow-shakespeare-master/cache/all_modern_train.ids
fr_train /home/trideep/Downloads/tensorflow-shakespeare-master/cache/all_original_train.ids
en_dev /home/trideep/Downloads/tensorflow-shakespeare-master/cache/all_modern_dev.ids
fr_dev /home/trideep/Downloads/tensorflow-shakespeare-master/cache/all_original_dev.ids
Creating 2 layers of 256 units.
en_vocab_size 10000
fr_vocab_size 10000
<function sampled_loss at 0x7f3cea7839b0>
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/trideep/Downloads/tensorflow-shakespeare-master/tensorshake/translate/translate.py", line 314, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/trideep/Downloads/tensorflow-shakespeare-master/tensorshake/translate/translate.py", line 311, in main
    train()
  File "/home/trideep/Downloads/tensorflow-shakespeare-master/tensorshake/translate/translate.py", line 165, in train
    model = create_model(sess, False)
  File "/home/trideep/Downloads/tensorflow-shakespeare-master/tensorshake/translate/translate.py", line 133, in create_model
    forward_only=forward_only)
  File "tensorshake/translate/seq2seq_model.py", line 138, in __init__
    softmax_loss_function=softmax_loss_function)
TypeError: model_with_buckets() got multiple values for keyword argument 'softmax_loss_function'

**Comment by aewhatley** [comment]
I got this exact same error, any help?

**Comment by tokestermw** [comment]
Not sure but the code probably won't work on newer TensorFlow.

It should work on 0.5.

**Comment by gangeshwark** [comment]
@trideeprath @aewhatley @tokestermw works when the seq2seq_model.py is replaced with the new tensorflow version file from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py

@tokestermw 
After training, the output is not correct.

INPUT: Good morning
OUTPUT: purposely purposely purposely ditty ditty ditty ditty ditty ditty ditty

INPUT : Four days will quickly steep themselves in night
OUTPUT : ditty ditty ditty ditty ditty descry descry descry descry descry descry descry descry descry descry

What is happening?

**Comment by tokestermw** [comment]
Cool, thanks.

There's been a few changes since 0.5 but don't have time to debug now.

MT is tricky since it uses a softmax on a large vocab. The Shakespeare dataset is small so the accuracy will be bad. However, your results look stuck at a weird minimum. Try adjusting the learning rate (usually smaller) or use Gradient Descent Optimizer and see how it goes. Also try a smaller vocab.

**Comment by tokestermw** [comment]
relevant issue in TensorFlow: https://github.com/tensorflow/tensorflow/issues/550
